NUM_GPUS: 8
TRAIN:
  MAX_EPOCH: 1000
  CHECKPOINT_PERIOD: 5
DATALOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 28
LOSS:
  LOSS_FUN: FocalLoss
  logits: False
MODEL:
  MODEL_NAME: F3Net
  FIND_UNUSED_PARAMETERS: True
  NUM_CLASSES: 2
  IMG_WIDTH: 299
  IMG_HEIGHT: 299
  LFS_WINDOW_SIZE: 10
  LFS_STRIDE: 2
  LFS_M: 6
  XCEPTION_CFG:
    PRETRAINED: ''
    ESCAPE: ''
OPTIMIZER:
  OPTIMIZER_METHOD: sgd
  BASE_LR: 0.002
  MOMENTUM: 0.9
SCHEDULER:
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.00002
  WARM_UP_lr: 0.00002
  WARMUP_EPOCHS: 5
DATASET:
  IMG_SIZE: 299
  TRAIN_AUGMENTATIONS:
    OneOf:
      ColorJitter:
      RandomBrightnessContrast:
      HueSaturationValue:
      CLAHE:
      RandomGamma:
      Sharpen:
    GaussNoise:
    HorizontalFlip:
    ImageCompression: [65, 80]
    RandomResizedCrop: [299, 299, [0.8, 1], [0.75, 1.33]]
    Normalize: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
