OUTPUT_AND_PATH: '/mnt/data/liyihui/face_data/DFDet/Output/f3net.txt'
INIT_METHOD: tcp://localhost:9888
NUM_GPUS: 1
TRAIN:
  MAX_EPOCH: 1000
  CHECKPOINT_PERIOD: 5
DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 28
LOSS:
  LOSS_FUN: FocalLoss
  logits: False
MODEL:
  MODEL_NAME: F3Net
  FIND_UNUSED_PARAMETERS: True
  NUM_CLASSES: 2
  IMG_WIDTH: 299
  IMG_HEIGHT: 299
  LFS_WINDOW_SIZE: 10
  LFS_STRIDE: 2
  LFS_M: 6
  XCEPTION_CFG:
    PRETRAINED: ''
    ESCAPE: ''
OPTIMIZER:
  OPTIMIZER_METHOD: sgd
  BASE_LR: 0.002
  MOMENTUM: 0.9
SCHEDULER:
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.00002
  WARM_UP_lr: 0.00002
  WARMUP_EPOCHS: 5
DATASET:
  ROOT_DIR: /mnt/data/liyihui/face_data/DFDet/
  TRAIN_INFO_TXT: /mnt/data/liyihui/face_data/DFDet/dataset_list/train_list.txt
  VAL_INFO_TXT: /mnt/data/liyihui/face_data/DFDet/dataset_list/val_list.txt
  TEST_INFO_TXT: /mnt/data/liyihui/face_data/DFDet/dataset_list/test_list.txt
  IMG_SIZE: 299
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        [
          ColorJitter,
          RandomBrightnessContrast,
          HueSaturationValue,
          CLAHE,
          RandomGamma,
          Sharpen
        ],
        GaussNoise,
        HorizontalFlip,
        ImageCompression,
        RandomResizedCrop,
        Normalize
      ]
    RANDOMRESIZEDCROP_PARAMS: [299, 299, [0.8, 1], [0.75, 1.33]]
    ROTATE_PARAMS: [10]
    COARSEDROPOUT_PARAMS: [10, 10]
    IMAGECOMPRESSION_PARAMS: [65, 80]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
TEST:
  ENABLE: True
  TEST_CHECKPOINT_PATH: '/mnt/data/liyihui/face_data/DFDet/model/F3Net_FFDF_c23.pyth'