DATASET:
  IMG_SIZE: 380
  TRAIN_AUGMENTATIONS:
    Resize: [380, 380]
    HorizontalFlip:
    Normalize: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
  TEST_AUGMENTATIONS:
    Resize: [380, 380]
    Normalize: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  MODEL_NAME: ResNet50
  PRETRAINED: imagenet
  NUM_CLASSES: 2
OPTIMIZER:
  OPTIMIZER_METHOD: adam
  BASE_LR: 0.0004
  ADAM_BETAS: [0.9, 0.999]
  EPS: 0.00000001
  WEIGHT_DECAY: 0.000001
SCHEDULER:
  SCHEDULER_TYPE: step
  DECAY_EPOCHS: 5
  DECAY_RATE: 0.5